DROP TABLE IF EXISTS inventory;
DROP TABLE IF EXISTS orderitem;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS product;
DROP TABLE IF EXISTS supplier;
DROP TABLE IF EXISTS store;
DROP TABLE IF EXISTS category;
DROP TABLE IF EXISTS customer;